[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crowdfunding = "FimdP5D6JqNEsqxUv1B9tA2XceKWbEnJ3BF7NWKse4Et"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/salifousayeabdouk./.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
